name: Test PR
on:
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
            - uses: ./.github/workflows/setup

    test:
        needs: [build]
        runs-on: ${{ matrix.runs-on }}

        strategy:
            fail-fast: true

            matrix:
                fixture:
                    - typescript,typescript-zod,typescript-effect-schema
                    - javascript,schema-javascript
                    - golang,schema-golang
                    - cjson,schema-cjson
                    - cplusplus,schema-cplusplus
                    - flow,schema-flow
                    - java,schema-java
                    - python,schema-python
                    - haskell,schema-haskell
                    - csharp,schema-csharp,schema-json-csharp,graphql-csharp,csharp-SystemTextJson
                    - json-ts-csharp
                    - dart,schema-dart
                    - swift,schema-swift
                    - javascript-prop-types
                    - ruby
                    - php
                    - scala3,schema-scala3

                    # Partially working
                    # - schema-typescript # TODO Unify with typescript once fixed

                    # Implementation is too outdated to test in GitHub Actions
                    # - elm,schema-elm

                    # Language is too niche / obscure to test easily on ubuntu-latest
                    # - pike,schema-pike

                    # Not yet started
                    # @schani can you help me understand this fixture?
                    # It looks like it tests 13+ languages?
                    # - graphql

                    # Never tested?
                    # - crystal

                runs-on: [ubuntu-latest]

                include:
                    # Rust is very slow, so we use a larger runner
                    - fixture: rust,schema-rust
                      runs-on: ubuntu-latest-8-cores
                    # Kotlin is also slow
                    - fixture: kotlin,schema-kotlin,kotlin-jackson,schema-kotlin-jackson
                      runs-on: ubuntu-latest-8-cores

                    - fixture: objective-c
                      runs-on: macos-11

        name: ${{ matrix.fixture }}
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
            - uses: ./.github/workflows/setup

            - name: Setup PHP
              if: ${{ contains(matrix.fixture, 'php') }}
              uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f  # v2
              with:
                  php-version: "8.2"

            - name: Setup Dart
              if: ${{ contains(matrix.fixture, 'dart') }}
              uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d  # v1.3
              with:
                  sdk: 2.14.4

            - name: Setup Swift
              if: ${{ contains(matrix.fixture, 'swift') }}
              uses: swift-actions/setup-swift@cdbe0f7f4c77929b6580e71983e8606e55ffe7e4  # v1
              with:
                  swift-version: "5.7.2"

            - name: Install Ruby
              uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64  # v1
              if: ${{ contains(matrix.fixture, 'ruby') }}
              with:
                  ruby-version: "3.2.0"

            - name: Setup .NET Core SDK
              if: ${{ contains(matrix.fixture, 'csharp') }}
              uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815  # v3
              with:
                  dotnet-version: 6

            - name: Install Rust
              if: ${{ contains(matrix.fixture, 'rust') }}
              uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af  # v1
              with:
                  toolchain: stable

            - name: Install Elm
              if: ${{ contains(matrix.fixture, 'elm') }}
              run: |
                  curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
                  gunzip elm.gz
                  chmod +x elm
                  sudo mv elm /usr/local/bin/
            - name: Install Haskell
              if: ${{ contains(matrix.fixture, 'haskell') }}
              run: |
                  if ! command -v stack > /dev/null 2>&1; then
                    curl -sL "https://get.haskellstack.org/" | sh
                  fi
            - name: Install Python 3.7
              if: ${{ contains(matrix.fixture, 'python') }}
              uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c  # v4
              with:
                  python-version: 3.7

            - name: Install Python Dependencies
              if: ${{ contains(matrix.fixture, 'python') }}
              run: |
                  pip3.7 install mypy python-dateutil types-python-dateutil
            - name: Install flow
              if: ${{ contains(matrix.fixture, 'flow') }}
              run: |
                  npm install -g flow-bin@0.66.0 flow-remove-types@1.2.3
            - name: Install Java
              if: ${{ matrix.fixture == 'java,schema-java' || contains(matrix.fixture, 'kotlin') }}
              uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62  # v3
              with:
                  java-version: "11"
                  distribution: "adopt"

            - name: Install Maven
              if: ${{ matrix.fixture == 'java,schema-java' }}
              uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f  # v4.5
              with:
                  maven-version: 3.8.2

            - name: Install Kotlin
              if: ${{ contains(matrix.fixture, 'kotlin') }}
              uses: fwilhe2/setup-kotlin@ff13a3c9bdd41729590546b4aacbb580ccc0aefc  # main

            - name: Install go
              if: ${{ contains(matrix.fixture, 'golang') }}
              uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495  # v3
              with:
                  go-version: 1.15

            - name: Install C
              if: ${{ contains(matrix.fixture, 'cjson') }}
              run: |
                  sudo apt-get update
                  sudo apt-get -y install build-essential valgrind

            - name: Install C++
              if: ${{ contains(matrix.fixture, 'cplusplus') }}
              run: |
                  sudo apt-get update
                  sudo apt-get -y install libboost-all-dev software-properties-common g++ --assume-yes

            - name: Install scala
              if: ${{ contains(matrix.fixture, 'scala3') }}
              uses: VirtusLab/scala-cli-setup@38df20348ed96678a702f535045753de021fb62c  # main
            - run: echo '@main def hello() = println("We need this spam print statement for bloop to exit correctly...")' | scala-cli _
              if: ${{ contains(matrix.fixture, 'scala3') }}

            - run: QUICKTEST=true FIXTURE=${{ matrix.fixture }} npm test

    test-complete:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - run: echo 🎉
